version: '3.4'
services:
  web:
    image: web:v1
    container_name: web
    depends_on:
      - catalogue
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  mongo:
    image: mongo:v1
    container_name: mongodb
  redis:
    image: redis
  user:
    image: user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
networks:
  roboshop:
    driver: bridge
    